model: "cnn"
optimizer: "adamw"
start_epoch: 1
end_epoch: 29
from_checkpoint: true
checkpoint_file: "last.pth"
batch_size: 256

model_cnn:
  image_shape: [3, 64, 64]
  channels: [3, 8, 16, 32]
  mlp_sizes: [2048, 1024, 512, 256]

optimizer_adamw:
  lr: 1e-4
  weight_decay: 0.05
  scheduler: "exponential"
  decay_rate: 0.1
  
loss:
  reconstruction: "mse"
  nodes: "probs"
  edges: "probs"
