model: "cnn"
optimizer: "adamw"
start_epoch: 0
end_epoch: 9
from_checkpoint: false
checkpoint_file: ""
batch_size: 256

model_cnn:
  image_shape: [3, 64, 64]
  channels: [3, 8, 16, 32]
  mlp_sizes: [2048, 1024, 512, 256]

optimizer_adamw:
  lr: 1e-5
  weight_decay: 0.05
  scheduler: "constant"

loss:
  reconstruction: "ssim"
  nodes: "probs"
  edges: "probs"
