model: "cnn"
optimizer: "adamw"
dataset: "coco"
start_epoch: 0
end_epoch: 29
from_checkpoint: false
checkpoint_file: "best.pth"
batch_size: 256
num_workers: 8

model_cnn:
  image_shape: [3, 64, 64]
  channels: [3, 8, 16, 32]
  mlp_sizes: [2048, 1024, 512, 256]

optimizer_adamw:
  lr: 1e-4
  weight_decay: 0.05
  scheduler: "exponential"
  decay_rate: 0.1

loss:
  reconstruction: "mae"
  nodes: "probs"
  edges: "probs"
